<?php
namespace Qwer\PromoBundle\Repository;

use Doctrine\ORM\EntityRepository;
use \MarketFusion\Bundle\DataBundle\Entity\User;

/**
 * PromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoRepository extends EntityRepository{
    
    /**
     * Get Promo by id
     * @param type $id
     * @return type
     */
    public function get ($id)
    {
        return $this->findOneBy (array ('id' => $id));
    }    
    
    public function findByUserId ($userId)
    {
        return $this->findBy(array('userId' => $userId));
    }
}
